src/AppBundle/Entity/Location.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Location
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Location
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="address_street", type="string", length=255)
     */
    private $addressStreet;

    /**
     * @var string
     *
     * @ORM\Column(name="address_plz", type="string", length=255)
     */
    private $addressPlz;

    /**
     * @var string
     *
     * @ORM\Column(name="address_location", type="string", length=255)
     */
    private $addressLocation;

    public function __toString()
    {
    	return $this->getName();
    }

    public function getAddress()
    {
    	return $this->getAddressStreet()."\r\n".$this->getAddressPlz().' '.$this->getAddressLocation();
    }
    
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Location
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Location
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set addressStreet
     *
     * @param string $addressStreet
     *
     * @return Location
     */
    public function setAddressStreet($addressStreet)
    {
        $this->addressStreet = $addressStreet;

        return $this;
    }

    /**
     * Get addressStreet
     *
     * @return string
     */
    public function getAddressStreet()
    {
        return $this->addressStreet;
    }

    /**
     * Set addressPlz
     *
     * @param string $addressPlz
     *
     * @return Location
     */
    public function setAddressPlz($addressPlz)
    {
        $this->addressPlz = $addressPlz;

        return $this;
    }

    /**
     * Get addressPlz
     *
     * @return string
     */
    public function getAddressPlz()
    {
        return $this->addressPlz;
    }

    /**
     * Set addressLocation
     *
     * @param string $addressLocation
     *
     * @return Location
     */
    public function setAddressLocation($addressLocation)
    {
        $this->addressLocation = $addressLocation;

        return $this;
    }

    /**
     * Get addressLocation
     *
     * @return string
     */
    public function getAddressLocation()
    {
        return $this->addressLocation;
    }
}


src/AppBundle/Form/TournamentType.php
<?php

namespace AppBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;

class TournamentType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    	//$data = $builder->getData();
//     	$players = $options['players'];
        $builder
            ->add('date', DateType::class, array(
            		'label' => 'Datum',
            		'required' => false,
            ))
            ->add('event', EntityType::class, array(
            		'label' => 'übergeordnete Veranstaltung',
            		'class' => 'AppBundle:Event',
            		'choice_label' => 'name',
            		'multiple' => false,
            		'expanded' => false,
            		'required' => false
            ))
            ->add('mainTournament', CheckboxType::class, array(
            		'label' => 'Hauptturnier zum Event',
            		'required' => false,
            	))
            ->add('name', TextType::class, array(
            		'label' => 'Veranstaltungsname',
            		'required' => false,
            ))
            ->add('description', TextareaType::class, array(
            		'label' => 'Beschreibung',
            		'required' => false,
            ))
            ->add('location', EntityType::class, array(
            		'label' => 'Veranstaltungsort',
            		'class' => 'AppBundle:Location',
            		'choice_label' => 'name',
            		'placeholder' => 'Veranstaltungsort auswählen',
            		'empty_data' => null,
            		'multiple' => false,
            		'expanded' => false,
            		'required' => false
            ))
//             ->add('ranking', 'collection', array(
//             		'type' => new RankingFieldType(),
//             		'label' => 'Plazierung',
//             		'options'  => array(
//             				'label' => false,
//             				'required'  => false,
//            		)
//             ))
            ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($builder)
            {
            	$form = $event->getForm();
            	$data = $event->getData();
            	$form->add('players', EntityType::class, array(
            			'label' => 'Teilnemer',
            			'class' => 'AppBundle:Player',
            			'data' => $data->getPlayers(),
            	        'query_builder' => function (EntityRepository $er) {
                	        return $er->createQueryBuilder('p')
                    	        ->addOrderBy('p.givenname', 'ASC')
                    	        ->addOrderBy('p.surname', 'ASC');
            	        },
            			'multiple' => true,
            			'expanded' => true,
            			'required' => false,
            			'mapped' => false
            	));
            });
        ;

//         if($data->getRanking()->count() == 0)
//         {
// 	        foreach ($players as $player)
// 	        {
// 	        	$builder
// 	        		->add('ranking_'.$player->getId(), new RankingFieldType(new TournamentRanking($data, $player)), array('mapped' => false));
// 	        }
//         }
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Tournament'
        ));
        
//         $resolver->setRequired(array('players'));
    }
    
    /**
     * @return string
     */
    public function getName()
    {
        return 'reu_pokernight_AppBundle_tournament';
    }
}

src/AppBundle/Controller/TournamentController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Tournament;
use AppBundle\Entity\TournamentManager;
use AppBundle\Entity\TournamentRanking;
use AppBundle\Form\AddRankingType;
use AppBundle\Form\TournamentType;
use Doctrine\Common\Collections\ArrayCollection;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\TournamentRanking\TournamentRankingManager;
use Doctrine\Common\Util\Debug;


/**
 * Tournament controller.
 *
 * @Route("/tournament")
 */
class TournamentController extends Controller
{
    
    /**
     * Creates a new Tournament entity.
     *
     * !! Form Action Target !!
     * 
     * @Route("/", name="tournament_create")
     * @Method("POST")
     * @Template("AppBundle:Tournament:new.html.twig")
     */
    public function createAction(Request $request)
    {
        /** @var TournamentManager $tournamentManager **/
        $tournamentManager = $this->get('bpn.tournament.manager');
        
        $entity = $tournamentManager->create();
        
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) 
        {
            $em = $this->getDoctrine()->getManager();
            $rankingRepo = $em->getRepository('AppBundle:TournamentRanking');
            $players = $form->get('players')->getData();

            $tournamentManager->update($entity, false);
            
            foreach ($players as $player)
            {
            	$ranking = $rankingRepo->findBy(array('tournament' => $entity, 'player' => $player));
            	if(empty($ranking))
            	{
            		$ranking = new TournamentRanking($entity, $player);
            		$em->persist($ranking);
            		$entity->addRanking($ranking);
            	}
            }
            $em->flush();

            return $this->redirect($this->generateUrl('tournament_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Tournament entity.
     *
     * @param Tournament $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Tournament $entity)
    {
        $form = $this->createForm(TournamentType::class, $entity, array(
            'action' => $this->generateUrl('tournament_create'),
            'method' => 'POST',
        ));

        $form->add('submit', SubmitType::class, array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Tournament entity.
     *
     * @Route("/new", name="tournament_new")
     * @Template()
     */
    public function newAction()
    {
        /** @var TournamentManager $tournamentManager **/
        $tournamentManager = $this->get('bpn.tournament.manager');
        
        $entity = $tournamentManager->create();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Tournament entity.
     *
     * @Route("/{id}", name="tournament_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        /** @var TournamentManager $tournamentManager **/
        $tournamentManager = $this->get('bpn.tournament.manager');
        
        $entity = $tournamentManager->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Tournament entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Tournament entity.
     *
     * @Route("/{id}/edit", name="tournament_edit")
     * @Template()
     */
    public function editAction(Request $request, $id)
    {
        /** @var TournamentManager $tournamentManager **/
        $tournamentManager = $this->get('bpn.tournament.manager');
        
        $entity = $tournamentManager->find($id);
        
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Tournament entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        $editForm->handleRequest($request);
        
        if($editForm->isSubmitted() && $editForm->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $rankingRepo = $em->getRepository('AppBundle:TournamentRanking');
            $players = $editForm->get('players')->getData();
            
            $tournamentManager->update($entity, false);
           
            // alte Spieler aus Ranking holen und nicht mehr teilnehmende TournamentRankings entfernen
            $oldPlayers = [];
            foreach($rankingRepo->findByTournament($entity) as $oldRanking)
            {
                $oldPlayers[] = $oldRanking->getPlayer(); 
            }
            $delete = array_diff($oldPlayers, $players);
            $rankingRepo->deleteByTournamentAndPlayerList($entity, $delete);
            
            // Ranking für Spieler anlegen
            foreach ($players as $player)
            {
                $ranking = $rankingRepo->findBy(array('tournament' => $entity, 'player' => $player));
                if(empty($ranking))
                {
                    $ranking = new TournamentRanking($entity, $player);
                    $em->persist($ranking);
                    $entity->addRanking($ranking);
                }
            }
            
            
            $em->flush();
            
            $tournamentManager->update($entity);
            $this->addFlash('success', "Turnier wurde erfolgreich bearbeitet.");
            return $this->redirectToRoute('tournament_show', array('id' => $id));
        }
        
        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Tournament entity.
    *
    * @param Tournament $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Tournament $entity)
    {
        $form = $this->createForm(TournamentType::class, $entity, array(
            'action' => $this->generateUrl('tournament_edit', array('id' => $entity->getId())),
        ));

        $form->add('submit', SubmitType::class, array('label' => 'Update'));

        return $form;
    }

    /**
     * Deletes a Tournament entity.
     *
     * @Route("/{id}", name="tournament_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            /** @var TournamentManager $tournamentManager **/
            $tournamentManager = $this->get('bpn.tournament.manager');
            
            $entity = $tournamentManager->find($id);
            
            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Tournament entity.');
            }
            
            $tournamentManager->remove($entity);
        }

        $this->addFlash('success', "Turnier erfolgreich gelöscht!");
        return $this->redirect($this->generateUrl('event_index'));
    }

    /**
     * Creates a form to delete a Tournament entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('tournament_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', SubmitType::class, array('label' => 'Delete'))
            ->getForm()
        ;
    }

    /**
     * @Route("/{tournamentId}/ranking", name="tournament_ranking_update")
     * @Template("AppBundle:Tournament:update_ranking.html.twig")
     */
    public function updateTournamentRankingAction(Request $request, $tournamentId)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('AppBundle:Tournament')->find($tournamentId);
        /** @var $tournamentRankingManager TournamentRankingManager **/
        $tournamentRankingManager = $this->get('bpn.tournament_ranking.manager');
        
        if (!$entity)
        {
            throw $this->createNotFoundException('Unable to find Tournament entity.');
        }
     
        $editForm = $this->createForm(AddRankingType::class, $entity, array(
                'label' => false,
        ))
            ->add('submit', SubmitType::class, array('label' => 'Update'));
        
        $editForm->handleRequest($request);
        if ($editForm->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            
            $tournamentRankingManager->refreshRanking($entity);
            
            return $this->redirect($this->generateUrl('administration_live', array('tournamentId' => $tournamentId)));
        }
        

src/AppBundle/Resources/views/Tournament/edit.html.twig
{% extends 'AppBundle::template_default.html.twig' %}

{% block subtitle %}Turniertverwaltung{% endblock %} 

{% block content %}
<div class="container">
	<div class="row">
		<div class="page-header">
			<h1>Turnier bearbeiten <small>{{ entity }}</small></h1>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-12">
			<div class="btn-group pull-left">
			  <a class="btn btn-default" href="{{ path('event_index') }}"><i class="fa fa-backward"></i> zurück zur Veranstaltungsübersicht</a>
			</div>{% if delete_form is defined %}
			<div class="btn-group pull-right">
				{{ form(delete_form) }}
			</div>{% endif %}
		</div>
	</div>
	
	<hr>
	<div class="row">
		<div class="col-lg-4 col-md-6 col-sm-12">
    		{{ form(edit_form) }}
    	</div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Tournament/form_tournament_ranking.html.twig
{% use 'bootstrap_3_layout.html.twig' %}

{% block ranking_field_row %}
<div class="form-group col-sm-12{% if (not compound or force_error|default(false)) and not valid %} has-error{% endif %}">
    
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>
{% endblock %}

{% block _add_ranking_ranking_entry_row %}
<div class="form-group col-sm-12{% if (not compound or force_error|default(false)) and not valid %} has-error{% endif %}">
        <h4>{{ form.vars.value.player }}</h4>
        
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>
{% endblock %}

{% block _add_ranking_ranking_entry_kickedByPlayer_row %}
<div class="form-group col-sm-6{% if (not compound or force_error|default(false)) and not valid %} has-error{% endif %}">
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>
{% endblock %}

{% block _add_ranking_ranking_entry_kickedAt_row %}
<div class="form-group col-sm-6{% if (not compound or force_error|default(false)) and not valid %} has-error{% endif %}">
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>
{% endblock %}




src/AppBundle/Resources/views/Tournament/new.html.twig
{% extends 'AppBundle::template_default.html.twig' %}

{% block subtitle %}Turnierverwaltung{% endblock %} 

{% block content %}
<div class="container">
	<div class="row">
		<div class="page-header">
			<h1>Turnier erstellen</h1>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-12">
			<div class="btn-group pull-left">
			  <a class="btn btn-default" href="{{ path('event_index') }}"><i class="fa fa-backward"></i> zurück zur Veranstaltungsübersicht</a>
			</div>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-lg-4 col-md-6 col-sm-12">
		    {{ form(form) }}
		</div>
	</div>
</div>
{% endblock %}

src/AppBundle/Resources/views/Tournament/show.html.twig
{% extends 'AppBundle::template_default.html.twig' %}

{% block subtitle %}Turnierdetails{% endblock %} 

{% block content %}
<div class="container">
	<div class="row">
		<div class="page-header">
			<h1>{{ entity }} <small>Detailansicht</small></h1>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-12">
			<div class="btn-group pull-left">
				<a class="btn btn-default" href="{{ path('event_index') }}"><i class="fa fa-backward"></i> zurück zur Veranstaltungsübersicht</a>
			</div>
			<div class="btn-group pull-right">
			  {{ form(delete_form) }}
			</div>
			<div class="btn-group pull-right">
			  <a class="btn btn-default" href="{{ path('tournament_edit', { 'id': entity.id }) }}"><i class="fa fa-fw fa-pencil"></i> Turnier bearbeiten</a>
			  <a class="btn btn-default" href="{{ path('tournament_ranking_update', { 'tournamentId': entity.id }) }}"><i class="fa fa-fw fa-list"></i> Plazierung bearbeiten</a>
			</div>
		</div>
	</div>
	
	<hr>
	<div class="row">
		<div class="col-sm-12 col-md-5">
		    <table class="table table-striped table-hover table-responsive">
		        <tbody>
		            <tr>
		                <th class="col-sm-5">Name</th>
		                <td class="col-sm-7">{{ entity.name }}</td>
		            </tr>
		            <tr>
		                <th>Datum</th>
		                <td>{{ entity.date|date('d.m.Y') }}</td>
		            </tr>
		            <tr>
		                <th>Ort</th>
		                <td>
		                	<strong>{{ entity.location }}</strong><br />
		                	<small>{{ entity.location.address | nl2br }}</small>
		                </td>
		            </tr>
		            <tr>
		                <th>Veranstaltung</th>
		                <td><a href="{{ path('event_show', { 'id': entity.event.id }) }}"><i class="fa fa-fw fa-tags"></i> {{ entity.event }}</a></td>
		            </tr>
		        </tbody>
		    </table>
		</div>
		
		<div class="col-sm-12 col-md-7">
			<div class="col-sm-12">
				<div class="list-group">
				  <a class="list-group-item active">
				    <h4 class="list-group-item-heading"><i class="fa fa-fw fa-trophy"></i> Plazierung ({{ entity.ranking | length }})</small></h4>
				  </a>
				{% for rank in entity.ranking %}
				  <a href="{{ path('player_show', { 'id': rank.player.id}) }}" class="list-group-item">
{# 					    <span class="pull-left badge{% if rank.rank == 1 %} badge-success">{% else %} badge-info">{% endif %}{{ "%d. Platz" | format(rank.rank) }}</span>#}
				    <p class="list-group-item-text">{{ "%d. " | format(rank.rank) }} <small>{{ rank.player }}</small></p>
				  </a>
	            {% else %}
				  <a class="list-group-item list-group-item-warning">
				    <p class="list-group-item-text">keine Spieler zugeordnet</p>
				  </a>
	            {% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

src/AppBundle/Resources/views/Tournament/update_ranking.html.twig
{% extends 'AppBundle::template_default.html.twig' %}

{% block subtitle %}Turniertverwaltung{% endblock %} 

{% block content %}
<div class="container">
	<div class="row">
		<div class="page-header">
			<h1>Turnierplatzierung bearbeiten <small>{{ entity }}</small></h1>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-12">
			<div class="btn-group pull-left">
			  <a class="btn btn-default" href="{{ path('event_index') }}"><i class="fa fa-backward"></i> zurück zur Veranstaltungsübersicht</a>
			</div>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-6 col-sm-12">
		      {% form_theme edit_form 'AppBundle:Tournament:form_tournament_ranking.html.twig' %}
    		{{ form(edit_form) }}
    	</div>
    </div>
{% endblock %}